# Generated by Django 5.2.7 on 2025-11-11 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='language',
            field=models.CharField(choices=[('ru', 'Русский'), ('en', 'English'), ('kk', 'Қазақша')], default='ru', max_length=2, verbose_name='Язык интерфейса'),
        ),
    ]
