# Generated by Django 5.2.7 on 2026-07-14 10:12

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_image_2_product_image_3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_2',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Изображение 2'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_3',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Изображение 3'),
        ),
    ]
