# Generated by Django 5.2.9 on 2025-12-02 15:43

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatDialog',
            fields=[
            ],
            options={
                'verbose_name': 'Диалог с клиентом',
                'verbose_name_plural': 'Мои Диалоги (Inbox)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
